# pinchflat: сгенерировано импортёром (runtipi); сеть external (создаёт cloudd), порты не публикуются.
networks:
  appnet:
    external: true
    name: ${APP_NET}
services:
  pinchflat:
    environment:
      BASIC_AUTH_PASSWORD: ${PINCHFLAT_BASIC_AUTH_PASSWORD}
      BASIC_AUTH_USERNAME: ${PINCHFLAT_BASIC_AUTH_USERNAME}
    image: keglin/pinchflat:v2025.6.6
    networks:
      appnet:
        aliases:
        - pinchflat_pinchflat_1
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/downloads:/downloads
