# jackett: сгенерировано импортёром (runtipi); сеть external (создаёт cloudd), порты не публикуются.
networks:
  appnet:
    external: true
    name: ${APP_NET}
services:
  jackett:
    environment:
      AUTO_UPDATE: 'true'
      PGID: '1000'
      PUID: '1000'
      TZ: ${TZ}
    image: lscr.io/linuxserver/jackett:latest
    networks:
      appnet:
        aliases:
        - jackett_jackett_1
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data:/config
    - ${ROOT_FOLDER_HOST}/media/torrents:/media/torrents
