# dropgate-server-umbrel: сгенерировано импортёром (umbrel); сеть external (создаёт cloudd), порты не публикуются.
networks:
  appnet:
    external: true
    name: ${APP_NET}
services:
  web:
    environment:
      ENABLE_P2P: 'true'
      ENABLE_UPLOAD: 'true'
      ENABLE_WEB_UI: 'true'
      SERVER_NAME: Dropgate Server
      SERVER_PORT: 52443
      UPLOAD_ENABLE_E2EE: 'true'
      UPLOAD_MAX_FILE_DOWNLOADS: 1
      UPLOAD_MAX_FILE_LIFETIME_HOURS: 24
      UPLOAD_MAX_FILE_SIZE_MB: 100
      UPLOAD_MAX_STORAGE_GB: 10
      UPLOAD_PRESERVE_UPLOADS: 'false'
    image: willtda/dropgate-server:3.0.13@sha256:43698790fe341ea3fb0094bbdca701ecdf875a9c4b9c92b67f86c34c887c132b
    networks:
      appnet:
        aliases:
        - dropgate-server_web_1
    restart: on-failure
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/uploads:/usr/src/app/uploads
