# fireshare: сгенерировано импортёром (runtipi); сеть external (создаёт cloudd), порты не публикуются.
networks:
  appnet:
    external: true
    name: ${APP_NET}
services:
  fireshare:
    environment:
      ADMIN_PASSWORD: ${FIRESHARE_PASSWORD}
      ADMIN_USERNAME: ${FIRESHARE_USERNAME}
      MINUTES_BETWEEN_VIDEO_SCANS: '5'
      PGID: '1000'
      PUID: '1000'
      SECRET_KEY: ${FIRESHARE_SECRET_KEY}
    image: shaneisrael/fireshare:1.7.7
    networks:
      appnet:
        aliases:
        - fireshare_fireshare_1
    restart: unless-stopped
    volumes:
    - ${APP_DATA_DIR}/data/fireshare_data:/data
    - ${APP_DATA_DIR}/data/fireshare_processed:/processed
    - ${ROOT_FOLDER_HOST}/media/data/videos/fireshare_videos:/videos
    - ${ROOT_FOLDER_HOST}/media/data/images/fireshare_images:/images
